/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatGuestRouteImport } from './routes/chat.guest'
import { Route as ChatSessionIdRouteImport } from './routes/chat.$sessionId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicChatGuestRouteImport } from './routes/api/public/chat-guest'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatGuestRoute = ChatGuestRouteImport.update({
  id: '/chat/guest',
  path: '/chat/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionIdRoute = ChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatGuestRoute = ApiPublicChatGuestRouteImport.update({
  id: '/api/public/chat-guest',
  path: '/api/public/chat-guest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/report': typeof ReportRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/chat/guest': typeof ChatGuestRoute
  '/chat/': typeof ChatIndexRoute
  '/api/public/chat-guest': typeof ApiPublicChatGuestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/report': typeof ReportRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/chat/guest': typeof ChatGuestRoute
  '/chat': typeof ChatIndexRoute
  '/api/public/chat-guest': typeof ApiPublicChatGuestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/report': typeof ReportRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/chat/guest': typeof ChatGuestRoute
  '/chat/': typeof ChatIndexRoute
  '/api/public/chat-guest': typeof ApiPublicChatGuestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/history'
    | '/report'
    | '/api/chat'
    | '/chat/$sessionId'
    | '/chat/guest'
    | '/chat/'
    | '/api/public/chat-guest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/history'
    | '/report'
    | '/api/chat'
    | '/chat/$sessionId'
    | '/chat/guest'
    | '/chat'
    | '/api/public/chat-guest'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/history'
    | '/report'
    | '/api/chat'
    | '/chat/$sessionId'
    | '/chat/guest'
    | '/chat/'
    | '/api/public/chat-guest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HistoryRoute: typeof HistoryRoute
  ReportRoute: typeof ReportRoute
  ApiChatRoute: typeof ApiChatRoute
  ChatSessionIdRoute: typeof ChatSessionIdRoute
  ChatGuestRoute: typeof ChatGuestRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ApiPublicChatGuestRoute: typeof ApiPublicChatGuestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/guest': {
      id: '/chat/guest'
      path: '/chat/guest'
      fullPath: '/chat/guest'
      preLoaderRoute: typeof ChatGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionId': {
      id: '/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof ChatSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat-guest': {
      id: '/api/public/chat-guest'
      path: '/api/public/chat-guest'
      fullPath: '/api/public/chat-guest'
      preLoaderRoute: typeof ApiPublicChatGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HistoryRoute: HistoryRoute,
  ReportRoute: ReportRoute,
  ApiChatRoute: ApiChatRoute,
  ChatSessionIdRoute: ChatSessionIdRoute,
  ChatGuestRoute: ChatGuestRoute,
  ChatIndexRoute: ChatIndexRoute,
  ApiPublicChatGuestRoute: ApiPublicChatGuestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
